### PR TITLE
Add more data points to graph, fix graph bugs

### LINKED ISSUE #819: Optimization graph doesn't show some builds
Currently, the Optimization Target vs. the selected Graph Target shows the maximum Optimization Target value only per 0.01 of the selected Graph Target. This makes it so that important builds can't be seen on the graph, effectively hiding away useful information. I'm suggesting that this "per 0.01" limitation is removed, or if that's unreasonable, then allow for up to 2-3 builds to be shown on the graph per 0.01 x-value.

### LINKED ISSUE #951: User should be able to highlight a build, even if it was generated by the Optimizer
This allows the user to highlight a generated build and keep it between optimization results

### LINKED ISSUE #952: User can highlight a build, even it is already highlighted, if it happens to be equipped

### LINKED ISSUE #997: Show highlighted builds on the graph even if they were not graphed originally

### PR DESCRIPTION
**Pull request by nguyentvan7**
* [x] Resolve #819
* [ ] Resolve #952 
* [ ] Resolve #951 
* [ ] Resolve #997

### CODE REVIEW

**Review by eeeqeee — CHANGES_REQUESTED** [review]
```
Failed to compile.

src/PageCharacter/CharacterDisplay/Tabs/TabOptimize/index.tsx
  Line 32:22:  'Build' is defined but never used  @typescript-eslint/no-unused-vars
```

**Comment by eeeqeee** [comment]
I'm seeing a 6x performance regression with this change. Perhaps there should be a way to select the number of y-values per x-value?

**Comment by nguyentvan7** [comment]
Hm when I tested, I only lost a flat 5 seconds, across simple and complex optimizations. I can test again and see

**Comment by nguyentvan7** [comment]
Prod: 
image

3-graph points: 
image

2 second increase over 55 second optimization/11 million builds

**Comment by eeeqeee** [comment]
ayaka in [this file](https://cdn.discordapp.com/attachments/819643218446254100/1059666165003198514/zzzzz22.json) is hitting the regression
it also seems to be bringing back #802

**Comment by frzyc** [comment]
Why not just retroactively add the built results builds onto the graph data? not sure why this churn is needed?

**Comment by nguyentvan7** [comment]
Branch is old and messed up somehow; recreating

**Pull request closed without merging**
