### PR TITLE
Equip filter is custom by default, add alert for teammate equipment in builds

### LINKED ISSUE #1625: Artifact Equipment filter update
In the old character-centric implementation of GO, the "equipped" build is used to resolve equipment of artifacts across several character. It made sense when optimizing, to use the non-equipped artifacts by default. Users can then opt-in to allow taking of artifacts from specific characters.

In the team loadout space, the usage of this feature is somewhat different. There is already a feature that by default disallow taking artifacts in teammates' active builds, which was partially what the equipment filter was trying to address(resolution of artifact equipment within a team). Since users can also save builds into loadouts for future reference, the equipment filter feature should be readdressed.

1. ~~adding a config button in artifact detail in generated build, next to single character exclusions, that shows the equipment filter (including tally). This should allow users to exclude singular equipment location, while being able to edit the whole list.~~ (probably overkill)
2. Remove the all/custom/none state of the artifact equipment filter. This should make it so that it is "all" by default(no one excluded). The none/all states are less relevant, and users should be encouraged to generate and save builds regardless of equipment.
3. when the "use teamate's active build" toggle is enabled, if a generated build has an artifact on an active build in the team, should an warning, similiar to https://github.com/frzyc/genshin-optimizer/pull/1556

### PR DESCRIPTION
**Pull request by frzyc**
## Describe your changes

- Make equipment filter "custom" by default, and remove other options (simplify logic)
- Add alert if build has artifact equipped on teammates

## Issue or discord link

- Resolves #1625

## Testing/validation
image
image

Screenshot 2024-05-01 145855

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Review by nguyentvan7 — COMMENTED** [review]
Screenshot_20240501_210951_Chrome
Screenshot_20240501_210700_Chrome

I can't see the indicators for some reason
[Van_2024-04-19_02-59-01.json](https://github.com/frzyc/genshin-optimizer/files/15183668/Van_2024-04-19_02-59-01.json)

Using ayakas only team, on the current settings

I can see the rest of the changes tho

**Comment by frzyc** [comment]
@nguyentvan7 I am not sure what the issue you have is. In the build you selected, you have an artifact equipped by ganyu, but ganyu is not part of your akaya team, so there is no "teammate equipped" indicator? If optimizer generated an artifact equipped by your kazuha, shenhe or layla, then the indicator will show.

**Comment by nguyentvan7** [comment]
I see it's for teammates only. If allowing from teammates is opt in only, why even have the alert specifically for that case, and not the case that is default enabled? I feel like it makes more sense to alert the user for default enabled cases, in case they missed it

**Comment by nguyentvan7** [comment]
Could you add the teammate equipped alert to the build swap preview too please?
Screenshot_20240501_210700_Chrome

**Comment by frzyc** [comment]
> I see it's for teammates only. If allowing from teammates is opt in only, why even have the alert specifically for that case, and not the case that is default enabled? I feel like it makes more sense to alert the user for default enabled cases, in case they missed it

Teammates make sense, because at the end of the day, you want to build a team with a valid, non-conflict build for each teammate, this warning helps resolve the build inside the team.

Creating and saving builds using equipped artifacts from outside the team is a behavior that we want to encourage, hence the "all" filter by default, showing a warning seems to go against that.

> Could you add the teammate equipped alert to the build swap preview too please?
I anticipate a larger overhaul of this UI https://github.com/frzyc/genshin-optimizer/issues/2054, and I would like to address this UI in that context, and not in this PR.

**Review by nguyentvan7 — APPROVED** [review]
I don't really get the reasoning but code is good enough

**Pull request merged**
