### PR TITLE
Add Emilie + weapon

### PR DESCRIPTION
**Pull request by nguyentvan7**
## Describe your changes

* Add Emilie
* Add her weapon
* Update gi-assets and sr-assets to depend on their respective assets-data:gen-file
* Updated some generated images (they were previously downloaded from ambr)

## Issue or discord link

- 

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Review by frzyc — COMMENTED** [review]
image
(not blocking)Would be nice to label this "Cleardew Cologne DMG"

**Review by frzyc — COMMENTED** [review]
Not blocking more of a nit:
add this as a teambuff conditional? (not convinced its worth the time to add honestly)
image

**Review by frzyc — APPROVED** [review]
LGTM all interactions looks to be working

**Comment by nguyentvan7** [comment]
> Not blocking more of a nit: add this as a teambuff conditional? (not convinced its worth the time to add honestly) image

We stopped adding conditionals/fields for things that dont matter, such as self res

**Comment by nguyentvan7** [comment]
> image (not blocking)Would be nice to label this "Cleardew Cologne DMG"

I think we also opted to not create special DMG strings unless needed (i.e. if A1 had multiple damage instances). ofc we can always change the precedent

**Pull request merged**
