### PR TITLE
Simplify nx task graph

### LINKED ISSUE #1325: Simplify nx task graph
The task dependency graph of our repo has gotten more and more complicated. This seeks to simplify and clean-house.
image
In this graph, `serve` should not depend on `build`, and building the frontend should certainly not require all dependency libs to be built.

Barring unique tasks, we should have 4 main "stages": `serve, `build`, `genFile`, `load-dm`.

- `build <- genFile <- load-dm`
- `serve <- genFile <- load-dm`

TODO list:
- [ ] do not make `serve` depend on `build`
- [ ] Eliminate `pipeline` task (should all be `genFile`
- [ ] rename `genFile` to `gen-file`
- [ ] document all the main tasks, as well as the nx structure in a wiki/readme

---
[Discord convo](https://discord.com/channels/785153694478893126/819643218446254100/1172011885269360680)

### PR DESCRIPTION
**Pull request by lantua**
## Describe your changes

House cleaning on nx graph.

Barring unique tasks, we should have 4 main "stages": `serve`, `build`, `genFile`, `load-dm`.

- `build <- genFile <- load-dm`
- `serve <- genFile <- load-dm`

TODO list:
- [x] do not make `serve` depend on `build`
- [x] Eliminate `pipeline` task (should all be `genFile`
- [x] rename `genFile` to `gen-file`
- [x] document all the main tasks, as well as the nx structure in a wiki/readme

## Issue or discord link

Resolves #1325

## Testing/validation

Updated `build`
image

Updated `serve`
image

Updated wiki:
https://github.com/frzyc/genshin-optimizer/wiki/Notes-on-nx-configuration

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [x] I have commented my code, in hard-to understand areas.
- [x] I have made corresponding changes to README or wiki.
- [x] For front-end changes, I have updated the corresponding English translations.
- [x] Ran `yarn run mini-ci` locally to validate format + lint.
- [x] If there were format issues, I ran `nx format write` to resolve them automatically.

### CODE REVIEW

**Comment by lantua** [comment]
Note: for sanity check `nx serve frontend` should still work even from a clean repo.

**Comment by lantua** [comment]
Add some wiki on the current nx task graph structure:
  https://github.com/frzyc/genshin-optimizer/wiki/Notes-on-nx-configuration

**Comment by frzyc** [comment]
`serve` doesn't run `gen-file` nor `load-dm` when it should.
image

**Review by frzyc — CHANGES_REQUESTED** [review]
`serve` doesn't run `gen-file` nor `load-dm` when it should. (empty task graph from nx graph)
image

**Review by frzyc — CHANGES_REQUESTED** [review]
I mean, it works, but to run a dev server, you are building production first, that makes no sense right? The ideal would be `serve` -> `gen-file` -> `load-dm` and not `serve` ->`build` -> `gen-file` -> `load-dm`
image

**Review by frzyc — APPROVED** [review]

**Review by nguyentvan7 — APPROVED** [review]

**Pull request merged**
