### PR TITLE
Refactor allowedAmpReactions, fix vape appearing for cryo multi-target

### LINKED ISSUE #528: Bug: Vape appearing as a option on Cryo characters on multi-target selector
image

### PR DESCRIPTION
**Pull request by nguyentvan7**
Fix #528 - Refactor allowedAmpReactions, fix vape appearing for cryo multi-target

### CODE REVIEW

**Comment by frzyc** [comment]
Characters with cryo-infusion should be able to melt 
image

**Comment by nguyentvan7** [comment]
Should be resolved

**Review by frzyc — CHANGES_REQUESTED** [review]
In `CustomMultiTarget.tsx`
image
When the infusion gets changed, and I guess, when optimization target is changed, then reaction should be reset to `undefined`, because you can change to a target that doesnt have reactions, but the toggle is still set to a reaction.

**Comment by nguyentvan7** [comment]
Done

**Review by frzyc — APPROVED** [review]

**Pull request merged**
