### PR TITLE
Redirect team JSON in multi-opt to team import page

### LINKED ISSUE #2228: Redirect user to team import when they try to import a team as a multi-opt
image

### PR DESCRIPTION
**Pull request by Kirk-KD**
## Describe your changes

When the user tries to import a Team JSON in the Mult Opt form, redirect the user to `/teams` and automatically pull up the Team Import modal and fills in the Team JSON.

## Issue or discord link

* Resolves #2228

## Testing/validation

Detecting and asking the user when they accidentally try to import a team:
image

Redirecting to `/teams` and automatically putting the JSON string in the modal:
image

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [x] I have commented my code in hard-to understand areas.
- [x] I have made corresponding changes to README or wiki.
- [x] For front-end changes, I have updated the corresponding English translations.
- [x] I have run `yarn run mini-ci` locally to validate format and lint.
- [x] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

## Summary by CodeRabbit

- **New Features**
	- Added a prompt for team imports, enhancing user guidance during the import process.
	- Improved navigation to the team import page based on validation results.
	- Automatically opens the import modal on the teams page when applicable.

- **Bug Fixes**
	- Enhanced error handling for invalid imports, providing clearer user feedback.

### CODE REVIEW

**Comment by Kirk-KD** [comment]
I don't know why "CL / format (pull_request)" keeps failing, I ran `yarn run mini-ci` before each commit and push.

**Comment by frzyc** [comment]
@Kirk-KD Try updating the `master` of your fork to the latest master. 
`format` CI compares changes from your current branch `2228` to your local `master` locally, but compares to repo `master` in the PR CI.

**Comment by Kirk-KD** [comment]
Merged and resolved conflict

**Comment by Kirk-KD** [comment]
I think I did something wrong in github, I will fix this asap when i get the chance, i may have merged something wrong.

**Comment by Kirk-KD** [comment]
Everything fixed

**Review by frzyc — APPROVED** [review]
LGTM, thanks for your work!

**Pull request merged**
