### PR TITLE
Update stat cards and optimize tab

### LINKED ISSUE #240: Rearrange character page stats
Now that the UI is moving to a 4 column layout change the character base/advanced/bonus stats into 3 seperate column UI elements and order to mimic the in-game stats page.

image
image

### LINKED ISSUE #450: Suggestion: Tweak to "bonus stats" on Overview and Optimize page
Bring the "reset" button inline with the rest of the site by making it red when a stat has been edited:
image

As mentioned in #251 make edited stats bold. But also add a single reset button next to the Edit Stats button to quickly reset all:
image

Then instead of #442. Add the teambuff and bonus stats as the new 4th column:
image

### PR DESCRIPTION
**Pull request by nguyentvan7**
## Enhancements
- Add more stats to the character Overview tab
- Resolve #240 - Rearrange Overview tab stats to line up more with in-game
- Change Overview tab stats to be 3-column/2-column depending on window width
image
image
image
- Add an indicator when a characters stats have been modified on the Overview tab
- Resolve #450 - Add a reset button to quickly reset all stats in a card
image

## Fixes
- Standardize enemy editor buttons with rest of site
- Fix stat inputs being too small to type in on certain window widths
image
- Fix excluded artifact count including the current characters artifacts
- Standardize appearance of cards in the Optimize tab
- Fix typo on home page
- Fix cursor styling on home page

## Technical
- Fix compile warnings on home page
- Fix console errors on home page

### CODE REVIEW

**Comment by nguyentvan7** [comment]
Still looking into adding a character's own buffs to the Optimize tab, alongside the team buffs and bonus stats. But not sure if it is going to be feasible

**Comment by StainAE86** [comment]
> Still looking into adding a character's own buffs to the Optimize tab, alongside the team buffs and bonus stats. But not sure if it is going to be feasible

Need to find a corner case with a character that has heaps of self buffs, along with weapon buffs, artifact buffs, team buffs and common bonus buffs just to see how bad it gets.

**Comment by nguyentvan7** [comment]
Yea my main difficulty is finding the buffs. I think it would only be feasible to pull the characters conditionals, but then there might be overlap between this and teambuffs card. Unless someone *cough Lantua, fixes the teambuff indicator being lost when accumulating. And even that might not be enough
The self-buffs card would certainly be another PR though

**Comment by nguyentvan7** [comment]
Removed changes here for history-keeping
- Change overview tab to 4-column on largest window width
- Add cards to display team buffs and custom stats in the Overview tab
image

**Comment by nguyentvan7** [comment]
Why was this closed?

**Comment by frzyc** [comment]
oh i attached it to a branch i just deleted, so it closed this as well...

**Comment by frzyc** [comment]
Huh, I couldn't reopen it unless the attached branch is added again. I just pushed 8.11.0 just so I can reopen this PR and retarget it to master

**Pull request closed without merging**
