### PR TITLE
Small improvements to CustomNumberInput

### PR DESCRIPTION
**Pull request by jeffy-g**
## Describe your changes

When editing artifacts, I felt it was inconvenient to enter substat, so I tried to improve the following points.

  + The selection color is the same color as the background color, making it difficult to see.

  + It is easier to change the value if the value is selected when the input element is focused

NOTE: The selection color is "red", but any color can be used as long as it contrasts with the element's background color.

## Issue or discord link

- 

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [x] I have commented my code in hard-to understand areas.
- [x] I have made corresponding changes to README or wiki.
- [x] For front-end changes, I have updated the corresponding English translations.
- [x] I have run `yarn run mini-ci` locally to validate format and lint.
- [x] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Comment by jeffy-g** [comment]
This is a stopgap implementation and not very smart.
It would be nice if it could be configured with mui. . .
Also, it would be nice if the `input` element could be made ready for input immediately after changing the substat item.

**Review by frzyc — CHANGES_REQUESTED** [review]
Fix useRef https://github.com/frzyc/genshin-optimizer/actions/runs/7932943920/job/21660570857#step:9:426
image

**Comment by jeffy-g** [comment]
Oops, my apologies for the oversight.
I forgot to import `useRef`.
I'm sorry for any inconvenience caused.

**Comment by jeffy-g** [comment]
Since `CustomNumberInput` is marked as deprecated and will likely be phased out in the near future,
I will be closing this PR. thanks

**Comment by frzyc** [comment]
Thanks for the contribution, I appreciated that you found something you found unsatisfying and made an active effort to change it.

**Pull request closed without merging**
