### PR TITLE
Add Traveler normal attacks to optimization targets

### LINKED ISSUE #641: Traveler normal attacks are missing from build results and optimization target selector

### PR DESCRIPTION
**Pull request by frzyc**
Fix #641 - Add Traveler normal attacks to optimization targets

### CODE REVIEW

**Review by nguyentvan7 — COMMENTED** [review]
Left comments

**Comment by nguyentvan7** [comment]
Oops, I submitted my review for the wrong PR. This is borked af, optimize button throws numerous errors and no builds are ever returned for any character, any optimization target

Or something is wrong with my dev environment, not sure
image

**Comment by nguyentvan7** [comment]
Hm jk it happens on any branch for some reason, even after npm install

**Comment by frzyc** [comment]
> Left comments

where?

**Review by nguyentvan7 — APPROVED** [review]

**Pull request merged**
