### PR TITLE
Fix Tc opt

### LINKED ISSUE #1519: TC Opt broken
https://discord.com/channels/785153694478893126/1200154094476734556/1210544028861333544

### PR DESCRIPTION
**Pull request by eeeqeee**
## Describe your changes

Fix #1519 

## Issue or discord link

- 

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Comment by frzyc** [comment]
huh, I am so confused

**Comment by eeeqeee** [comment]
wait is tc-opt working on https://genshin-optimizer-prs.github.io/pr/beta/frontend/ for you?

**Comment by nguyentvan7** [comment]
It doesn't work, I just didn't get how this fixed it

**Comment by eeeqeee** [comment]
importing `@genshin-optimizer/gi/ui` pulls in a library breaks in workers. (i think it was mui, but i deleted the debug files yesterday)

**Comment by frzyc** [comment]
I think the formal solution is to move react elements out of `uiData.tsx`, so we can rename it to `uiData.ts`

**Comment by frzyc** [comment]
Hmm, even knowing the source of the issue, I am honestly quite baffled to how you debug this. Can you also provide some information to how you traced/debugged this issue? as a learning opportunity?

**Review by frzyc — APPROVED** [review]
I don't mind merging this in just to fix tc opt, but I want to see if we can find an alternative to this solution in the future.

**Comment by eeeqeee** [comment]
> Hmm, even knowing the source of the issue, I am honestly quite baffled to how you debug this. Can you also provide some information to how you traced/debugged this issue? as a learning opportunity?

`assets/optimizeTcWorker-7789529e.js` starts with `(function(){var u6=document.createElement("style");`. This looked like MUI, so starting from `optimizeTcWorker` i looked for transitive imports that could pull in MUI. I compared files pulled in by the loadouts commit and the previous commit and tracked it to `uiData.tsx`

**Pull request merged**
