### PR TITLE
ad refactoring, adding in-content ad to loadout setting

### PR DESCRIPTION
**Pull request by frzyc**
## Describe your changes

Refactor ads
- add in-layout ad to loadout setting (next to empty space next to "equipped build") with different `dataAdSlot` id for experiment
- fake ads better fill up the ad space
- Allow full-width ads (header/footer banner ads)

## Issue or discord link

- 

## Testing/validation

Screenshot 2024-04-28 223409
Screenshot 2024-04-28 223518

IRL ad:
image

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Comment by nguyentvan7** [comment]
More? The current ones already feel a bit intrusive and change the feel of the site tbh

**Comment by frzyc** [comment]
> More? The current ones already feel a bit intrusive and change the feel of the site tbh

The [mid-page ad](https://theonlineadvertisingguide.com/ad-size-guide/300x250/) is probably more important to have than "border ads" that have been implemented, That's why there is a separate ad id for this one, to compare the RPM across different ad units. In terms of your concern of intrusiveness, I understand what you mean, This is using up a space that is otherwise empty.

**Comment by nguyentvan7** [comment]
It's less about the space and more about the glaring white bg

**Review by nguyentvan7 — APPROVED** [review]

**Comment by frzyc** [comment]
> It's less about the space and more about the glaring white bg
Can't really do too much with actual ads, since those are either an image or iframed.
For the GO-ads, I don't like the white color either. We can rework them to be less ugly in another PR: https://github.com/frzyc/genshin-optimizer/issues/2048

**Pull request merged**
