### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by frzyc**
## Describe your changes

Migrate nx to the latest version (17.2.7)
`nx migrate latest`
`yarn`
`yarn nx migrate --run-migrations`

delete `migrations.json`

remove `gh-pages` (now we have pipeline)

Update yarn version

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code, in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] Ran `yarn run mini-ci` locally to validate format + lint.
- [ ] If there were format issues, I ran `nx format write` to resolve them automatically.

### CODE REVIEW

**Comment by eeeqeee** [comment]
Why did the zips in `.yarn/cache/` change when the version didn't change in commit 0d7c51206a1d7fd5c412bed179cea5ddd3e6f193?

**Comment by frzyc** [comment]
I honestly don't know. It is jumping from yarn v3 to v4 so I assumed there is something there.

**Comment by eeeqeee** [comment]
fyi https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/#rule-breaking-changes

> Several rules were changed in significant enough ways to be considered breaking changes:
>
> Previously deprecated rules are deleted (chore(eslint-plugin): remove deprecated rules for v6):
>
> @typescript-eslint/no-duplicate-imports, replaced by imports/no-duplicates

**Comment by frzyc** [comment]
Been working on the `imports/no-duplicates` conversion for quite some time, a lot of weird errors popping up, maybe this version bump is more work than anticipated...

**Pull request closed without merging**
