### PR TITLE
ui json change

### PR DESCRIPTION
**Pull request by k-parihar**
## Describe your changes

Added required key value pair, Nothing removed.

```diff
- "builds": "Builds"
+ "builds": "Builds",
+ "upopt" : "Artifact Upgrader"
```

## Issue or discord link
[issue#2294](https://github.com/frzyc/genshin-optimizer/issues/2294)

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [x] I have commented my code in hard-to understand areas.
- [x] I have made corresponding changes to README or wiki.
- [x] For front-end changes, I have updated the corresponding English translations.
- [x] I have run `yarn run mini-ci` locally to validate format and lint.
- [x] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Comment by nguyentvan7** [comment]
Sorry that fix I suggested is wrong. Can you revert your change, and instead change this
https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/localization/assets/locales/en/page_character.json#L9
to be `upopt` as the key, instead of `upgradeopt`

and need to change this as well https://github.com/frzyc/genshin-optimizer/blob/87ba9f1bebd6d35c61e57c7aa03b9aba351940ba/libs/gi/page-team/src/CharacterDisplay/Content.tsx#L321

**Comment by k-parihar** [comment]
Hi @nguyentvan7,
Reverted the previous change, added changes in 
>1. https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/localization/assets/locales/en/page_character.json#L9
>1. [genshin-optimizer/libs/gi/page-team/src/CharacterDisplay/Content.tsx](https://github.com/frzyc/genshin-optimizer/blob/87ba9f1bebd6d35c61e57c7aa03b9aba351940ba/libs/gi/page-team/src/CharacterDisplay/Content.tsx#L321)

Please check and let me know if anything else needs to be done.

**Review by nguyentvan7 — APPROVED** [review]
looks good, thanks!

**Comment by k-parihar** [comment]
thanks :)

**Pull request merged**
