### PR TITLE
Experimenting with character card layout

### PR DESCRIPTION
**Pull request by HassnHamada**
## Describe your changes
Add the currently equipped build to each team

## Issue or discord link

#1552

## Testing/validation

1200x693@18

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Comment by frzyc** [comment]
This is a very interesting and cool idea, I like the fact that its not inherently taking up a ton of extra space(until its expanded).
Some first thoughts(not demanding an answer, just more noting down thoughts):
- The expanded equipment(2x3) might be a tad big. We can probably reuse the layout from the character card (1x6)
- What happens if the "Active build" is a TC build?
- This creates more of an association of the build with the team, when we want to associate the build with the loadout(since builds are stored per loadout). in a loadout, all the teams actually have the same "active build", since they are using the same loadout.

**Comment by HassnHamada** [comment]
* I just tried it and it defently looks cleaner
* I'm using `TeamCharacterDataManager.getLoadoutArtifacts` and `TeamCharacterDataManager.getLoadoutWeapon` currently they return nothing if the active build is a TCBuild I'll look into them image
* Yes It makes so much more sense to have it per loadout instead of per team. My idea is to move it on the top of the teams as a separate card

**Comment by HassnHamada** [comment]
## TC Build
Screenshot 2024-03-08 at 1 13 31 AM

## Normal Build
Screenshot 2024-03-08 at 1 15 36 AM

I'm think of removing all the hovering cards since they always show the "equipped" not what is actually active. And I'll also think of a way show the artifacts in batter "smaller" style 
Screenshot 2024-03-08 at 1 15 44 AM

**Comment by HassnHamada** [comment]
@frzyc How do I get the status of the current loadout? I can do it manually by adding the status of each piece of artefact, the set effect, and the weapon. I'm just asking if there is an easier way, or should I just remove the status section? 

Screenshot 2024-03-10 at 10 08 17 PM
Screenshot 2024-03-10 at 10 08 09 PM

**Comment by frzyc** [comment]
@HassnHamada For single character only calculations, you can use `useCharData` and feed it the build via `overrideArt` and `overrideWeapon`. We prefer to do genshin calculations using the engine itself, rather than calculating it manually on the UI side.

**Comment by HassnHamada** [comment]
@frzyc I don't have any more plans for this if you think there is any UI changes that need to be done or bad implementations just inform me I'll work on it 💪

**Comment by frzyc** [comment]
I think you make a good point about how the teamcard does not show the "loadout character" but the "equipped". In the character editor, I think you are right to disable the hover.

In the teams UI, I am going to make the hover show the loadout name + active build on that loadout.

**Comment by frzyc** [comment]
I appreciate all the effort you went into iterating on the design, and you definitely presented a lot of possibility towards evolving UI here, but I think ultimately we need to keep the focus of this UI to what's important(showing loadouts and associating them with teams). I think we can leverage some of your UI ideas to other parts of the UI(especially parts that show builds, maybe)

**Pull request closed without merging**
