### PR TITLE
add a delete button to the artifact editor

### LINKED ISSUE #2091: Add a delete button to Artifact Editor
Allows deleting artifact directly from the editor
Complexity will have to do with dup detection, allowempty state etc from the artifact editor

### PR DESCRIPTION
**Pull request by frzyc**
## Issue or discord link

- Resolves #2091

## Testing/validation

image

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Review by nguyentvan7 — DISMISSED** [review]
Delete button is enabled for artifacts that you are still in the process of creating. Not really an issue, but feels a bit strange since the Clear button does the same thing

**Comment by frzyc** [comment]
> Delete button is enabled for artifacts that you are still in the process of creating. Not really an issue, but feels a bit strange since the Clear button does the same thing

It shouldn't? it should only be enabled for edited artifact, or artifact that detects a dup

**Comment by nguyentvan7** [comment]
It was definitely enabled, I clicked add new artifact and filled out the fields and the delete button lit up and worked

**Comment by frzyc** [comment]
> It was definitely enabled, I clicked add new artifact and filled out the fields and the delete button lit up and worked

You are right, there is a bug with the id detection. Good catch.

**Review by nguyentvan7 — APPROVED** [review]

**Pull request merged**
