### PR TITLE
Refactor a lot of stuff, fix some bugs

### LINKED ISSUE #256: Favonius weapons (that have no calculatable passive) leave an unused UI element on the equipment tab
image

### LINKED ISSUE #276: Talent/Artifact conditionals need to be nested/combined
Some characters have mutliple contitionals per talent which is making the team buff page excessively long on smaller displays as each conditional option causes the talent title to repeat.

image

VV is also a huge culprit for this. That combined with poor contrast on the Element type colour is causing this to be a large issue.

image

### LINKED ISSUE #324: Unify Sheet Utility functions
Some of our template functions for cheets needs to be refactored. This is the proposed format:
```
charTemplates(cKey:CharacterKey, assets:Partial<Record<TalentSheetElementKey,string>>):{
  tr: (key:string) => Displayable
  trm: (key:string, value?:object) => Displayable
  talentTemplate: (talentKey, docsection:DocumentSection[]) => TalentSheetElement
  sectionTemplate: (Partial<DocumentSection>) => DocumentSection
  conditionalTemplate:(talentKey,conditional:Partial<Iconditional>) => Iconditional
}
```

### LINKED ISSUE #337: Suggestion: Compress the Default Artifact Set Effects popup
Since there is no need to see the 2-Set effect and 4-Set titles are irrelevant and inconsistent #336

I suggest removing everything but the checkbox for the 4-Set conditional on these artifact cards.
This will compress the popup significantly allowing for more to appear on one screen reducing the need to scroll so much.

(Also make the "Reset All" red to be in-line with other colours as per #319 )
image

@nguyentvan7 might already be doing this within #324
If the loss of the (i) for the tooltip is a problem - could put the (i) next to the artifact set name in the gradient area.

### PR DESCRIPTION
**Pull request by nguyentvan7**
Refactor sheet utility functions - Fix #324 
Refactor sheets
Refactor DocumentDisplay and all the related types
Refactor conditional
Refactor header to be required on conditionals
Refactor description to be a part of the header, rather than the section
Standardize/refactor header display
Fix some random bugs in some sheets (Venti C6, can't remember what else)
Add some new fields in some sheets (Raiden resolve stacks, Kokomi C2)
Fix some random display issues related to DocumentDisplay
Equipment tab now shows headers with description tooltips for everything - fixes #256 
Change `ArtConditionalModal` to use standardized headers to reduce white space - resolves #337 and #336
Move tooltip for 4-set to the gradient header in `ArtConditionalModal`

Update elemental colored text/icons in buttons/labels/a bunch of places to improve contrast
Refactor/standardize info/question mark tooltips

Hide conditional's header when in its own talent card
Adjust Bennett ult display to be clearer
Remove padding on `ConditionalSelector`
Fix artifact conditional modal not showing fields - Fix half of #351 - ty @lantua :)
-> There is still a todo here, not sure of the answer to it
Add multiple-state conditional selector for VV and Kazuha - Fixes #276

### CODE REVIEW

**Comment by nguyentvan7** [comment]
Should be good to review, barring any other sudden refactor needs

**Comment by frzyc** [comment]
image
image
Bennett is a tad in consistent here. the bonux shown is 119%+20%, but the actual increase being calculated is 119%

**Comment by frzyc** [comment]
image
image
What do you think about removing the extra padding around the `ConditionalSelector` ? I always felt they are a bit waste of space...
image

**Comment by frzyc** [comment]
I don't think this PR is complete until we can resolve #351

**Comment by nguyentvan7** [comment]
> image image Bennett is a tad in consistent here. the bonux shown is 119%+20%, but the actual increase being calculated is 119%

I don't follow. Formula shows 119+20, and the field shows 139, and the calculated value is 139% of attack, so all seem consistent. Or do you mean his burst field should only show 119%, and leave the 20% value in his c1 fields?

**Comment by frzyc** [comment]
> > image image Bennett is a tad in consistent here. the bonux shown is 119%+20%, but the actual increase being calculated is 119%
> 
> I don't follow. Formula shows 119+20, and the field shows 139, and the calculated value is 139% of attack, so all seem consistent. Or do you mean his burst field should only show 119%, and leave the 20% value in his c1 fields?

Opps, i did not snip the whole thing.
image
The total increase is 1002.3, however, if you look at both, you can get mislead to see 1002.3+144.22

**Comment by nguyentvan7** [comment]
Ready again

**Pull request merged**
