### PR TITLE
Clear search query after character selection window close

### LINKED ISSUE #1541: Clear previous query from searchbox when adding subsequent characters
image

### PR DESCRIPTION
**Pull request by HassnHamada**
## Describe your changes

Clear character search query when window closes.

## Issue or discord link

Resolves #1541

## Testing/validation

_1500X826@24

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [x] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Review by nguyentvan7 — APPROVED** [review]

**Comment by frzyc** [comment]
I think we can give [this](https://github.com/frzyc/genshin-optimizer/issues/1541#issuecomment-1963037231) a try, if it proves too difficult, we can default to this solution

**Comment by nguyentvan7** [comment]
`keepMounted` is default false already

**Comment by frzyc** [comment]
> `keepMounted` is default false already

Hmm, I guess its persisted because its in a state in a component that contains the modal. The way to use `keepMounted` is probably to refactor the modal content into another component so the state can be unmounted by the modal.

**Review by frzyc — APPROVED** [review]

**Comment by frzyc** [comment]
LGTM then, the "quick" solution turns out to be a noisier refactor.

**Pull request merged**
