### PR TITLE
Revamp team UI header

### PR DESCRIPTION
**Pull request by frzyc**
## Describe your changes
The buttons on the header of the team UI seems to be very loud, and there is not a visual distinction between "team actions" and "character actions". 

- Converting header buttons to outline buttons (and provide a lighter background so show button contrast still).
- Use the character's element for character specific buttons.
- Loadout/build setting button use the full width, so longer names would not cause too much layout shift.
- Character tabs selector to use the character's background.
- lighten the hydro + geo color to increase contrast.

## Issue or discord link

- Resolves https://github.com/frzyc/genshin-optimizer/issues/1756
## Testing/validation

image
image

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Review by nguyentvan7 — COMMENTED** [review]
I don't like bar.png and colored buttons. I'm ok to merge without those changes, and consider bar.png and colored buttons another time

**Comment by frzyc** [comment]
@nguyentvan7 How about this? lets hit a compromise. I will remove the bar.png but keep the colored buttons.

**Comment by nguyentvan7** [comment]
I still don't like colored buttons. they dont hint anything imo and just create noise. We don't have this design pattern anywhere else that color -> character. this + bar.png just seem like design flair, but they make the UI harder to parse

**Comment by frzyc** [comment]
> I still don't like colored buttons. they dont hint anything imo and just create noise. We don't have this design pattern anywhere else that color -> character. this + bar.png just seem like design flair, but they make the UI harder to parse

Reverting them back to the cyan buttons will be more noisy, since it would be

Elemental color team selector
CYAN
CYAN
elemental tab selector
image

I don't agree with the whole "don't hint anything", since it doesn't really say why you don't like it, other than a denial towards my reasoning. 

I don't think the "we don't have this design pattern anywhere else" is not a good reason to block this either, since we should not be limited by arbitrary "established convention" when we can be constantly trying to challenge it as an evolving product, and we can't have "established convention" without at least introducing it somewhere.

**Review by nguyentvan7 — APPROVED** [review]

**Review by nguyentvan7 — APPROVED** [review]

**Pull request merged**
