### PR TITLE
fix: team_loadout migration error

### PR DESCRIPTION
**Pull request by andrewdge**
## Describe your changes

reorder id col in _team_loadout.sql to fix deployment issue

## Issue or discord link

--

## Testing/validation

nx start gi-supabase runs successfully

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [x] I have commented my code in hard-to understand areas.
- [x] I have made corresponding changes to README or wiki.
- [x] For front-end changes, I have updated the corresponding English translations.
- [x] I have run `yarn run mini-ci` locally to validate format and lint.
- [x] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Review by frzyc — APPROVED** [review]
LGTM

**Comment by andrewdge** [comment]
how do i merge lol

**Comment by nguyentvan7** [comment]
Repo maintainers do it

**Comment by frzyc** [comment]
Was waiting for CI to pass

**Pull request merged**
