### PR TITLE
Add indicator for current build/equipped in generated builds

### PR DESCRIPTION
**Pull request by frzyc**
## Describe your changes

Show whether a generated build is equipped (and if its a saved build)
image

Show whether a generated build is the "current build" (and if multiple builds match)
image

Update Opt Graph
image

## Issue or discord link

- Resolves https://github.com/frzyc/genshin-optimizer/issues/1592

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Comment by arquelion** [comment]
Since the current behavior of the "Equip Build" button is to equip to the currently active build (which may not necessarily be the same as the equipped build), shouldn't the button be enabled in the first image and disabled in the second instead?

(I hope you don't mind my sticking my nose in. I've been working on adding the full swap preview when equipping over an existing build and ran into a related issue with the "Equip Build" button, popped in to see if you'd happened to address this already as part of this PR.)

**Comment by frzyc** [comment]
> Since the current behavior of the "Equip Build" button is to equip to the currently active build (which may not necessarily be the same as the equipped build), shouldn't the button be enabled in the first image and disabled in the second instead?
> 
> (I hope you don't mind my sticking my nose in. I've been working on adding the full swap preview when equipping over an existing build and ran into a related issue with the "Equip Build" button, popped in to see if you'd happened to address this already as part of this PR.)

You are completely right. this is a mistake on my side.

**Comment by arquelion** [comment]
I forgot to open an official issue for it since I was trying to dig for a solution, but it was almost identical now that I think about it. The button would remain enabled after equipping to the currently active build when the active build wasn't the same as the equipped build until after I refreshed the page.

I do have a closely related issue where my preview of the currently active build won't update either until after the refresh, something about the old `buildEquippedArtifactIds` and `buildEquippedWeaponId` values not being re-computed despite the changes to the database from `equipBuild`. Hopefully this will also be indirectly resolved in the process.

**Comment by frzyc** [comment]
> I forgot to open an official issue for it since I was trying to dig for a solution, but it was almost identical now that I think about it. The button would remain enabled after equipping to the currently active build when the active build wasn't the same as the equipped build until after I refreshed the page.
> 
> I do have a closely related issue where my preview of the currently active build won't update either until after the refresh, something about the old `buildEquippedArtifactIds` and `buildEquippedWeaponId` values not being re-computed despite the changes to the database from `equipBuild`. Hopefully this will also be indirectly resolved in the process.

Seems like an update issue, I'd say in situation like this, always defer to creating an issue, it will be more visible.

**Comment by nguyentvan7** [comment]
image
i currently have this build Equipped, and I am on my Equipped build. but it is saying that "vsva" is my current build, which doesn't seem right

**Comment by nguyentvan7** [comment]
image

I have this build as both "bkj" and "kbkj" saved. but it only shows as "bkj". I also think just inserting the build name here is a little confusing. What if we changed the badge to be a badge with a constant label, then when you hover, it shows you all the builds that it matches?

**Review by nguyentvan7 — COMMENTED** [review]
see previous comments

**Comment by frzyc** [comment]
> see previous comments

Forgot to push the code. Basically did what you suggested, have a popup that shows the matching builds, if there are multiple.

**Review by nguyentvan7 — APPROVED** [review]

**Pull request merged**
