### PR TITLE
Remove pipeline

### PR DESCRIPTION
**Pull request by frzyc**

### CODE REVIEW

**Comment by nguyentvan7** [comment]
Saw you getting rid of pipeline imports. What about these ones in all character `index.tsx`

image

**Comment by frzyc** [comment]
> Saw you getting rid of pipeline imports. What about these ones in all character `index.tsx`
> 
> image

This one is intended to know the shape of characterData. The imports i removed should be using the in-repo `const` definition that was wrongly imported.

**Comment by lantua** [comment]
Should we use `data` instead of `dm` in index files? It'll become obscure name afterward otherwise.

**Comment by frzyc** [comment]
> Should we use `data` instead of `dm` in index files? It'll become obscure name afterward otherwise.

I was going to use `data` but there were variables named data in those files, we can always rename later.

**Comment by nguyentvan7** [comment]
`talentValues`, `tv`, etc also work, since `data` variable name is already used

**Review by lantua — APPROVED** [review]

**Review by nguyentvan7 — APPROVED** [review]

**Pull request merged**
