### PR TITLE
Add pagination to Swap Artifact UI and changed artifact totals to reflect only artifacts for slot being swapped

### PR DESCRIPTION
**Pull request by arquelion**
## Describe your changes
- Added pagination to the Swap Artifact UI so all artifacts for the slot being swapped are displayed across multiple pages instead of only the first 12
- Added "Showing x out of y/z Artifacts" text clarifying how many artifacts are being shown (x), how many are being filtered (y), and how many match the selected slot (z)
- Modified `ArtifactFilterDisplay` to check whether the slot filter is disabled (as it is when swapping artifacts) and to only increment totals for artifacts matching the specified slot if it is - This results in the artifact totals in the Swap Artifact UI accounting for only that slot instead of using the count for the entire inventory (e.g. you'll see 0 instead of 0/x for filter options that don't actually exist in a slot).

## Issue or discord link

- https://github.com/frzyc/genshin-optimizer/issues/963

## Testing/validation

image
image
image
image
image
image

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [x] I have commented my code, in hard-to understand areas.
- [x] I have made corresponding changes to README or wiki.
- [x] For front-end changes, I have updated the corresponding English translations.
- [x] Ran `yarn run mini-ci` locally to validate format + lint.
- [x] If there were format issues, I ran `nx format write` to resolve them automatically.
- [x] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Comment by arquelion** [comment]
A sidenote: I'm inclined to agree that pagination for artifact-related things should probably be its own component as I honestly lifted a lot of the pagination stuff here directly out of the code for the Artifacts page (and there are quite a number of code similarities between the two). I could try to do it as part of this PR, but I personally thought it better to submit this as-is to address #963 and leave the refactor as a separate item.

**Comment by frzyc** [comment]
Looks like you need to run `nx format write` again

**Comment by frzyc** [comment]
my bad, `nx format` is comparing to the `master` of the repo, since you are working the master of your fork, it is itself. In this case, the command is `nx format write --base=upstream/master` to compare with the main repo. I would recommend in the future, to create a feature branch on your fork.

**Comment by arquelion** [comment]
Yeah I realized right before I was about to open the PR that I'd derped and forgotten to create a feature branch haha. I did wonder if that might've had something to do with it, so good to know.

**Comment by nguyentvan7** [comment]
https://genshin-optimizer-prs.github.io/pr/1436/frontend/

**Review by frzyc — APPROVED** [review]

**Pull request merged**
