### PR TITLE
Allow invisible backdrop click-through

### LINKED ISSUE #1497: Create a custom Dialog override to prevent overlay race condition
Similar to #967, we need to modify Dialog to use Popper instead of Popover or something similar. The backdrop is getting stuck on certain race conditions which renders the whole site unusable.

Probably related to https://github.com/mui/material-ui/issues/32286

### PR DESCRIPTION
**Pull request by frzyc**
## Issue or discord link

- Resolves #1497

## Checklist before requesting a review (leave this PR as draft if any part of this list is not done.)

- [ ] I have commented my code in hard-to understand areas.
- [ ] I have made corresponding changes to README or wiki.
- [ ] For front-end changes, I have updated the corresponding English translations.
- [ ] I have run `yarn run mini-ci` locally to validate format and lint.
- [ ] If I have added a new library or app, I have updated the deployment scripts to ignore changes as needed

### CODE REVIEW

**Comment by nguyentvan7** [comment]
Doesn't work

**Comment by nguyentvan7** [comment]
Here is the blocking element 
image

**Comment by nguyentvan7** [comment]
If you're willing to investigate more, I definitely think its related to the re-render cycle caused by applying KQMS

**Comment by frzyc** [comment]
> If you're willing to investigate more, I definitely think its related to the re-render cycle caused by applying KQMS

I don't think it's that simple, since I did add a timout with applying the KQMS as one experiment, with varying success. Its probably not worth the time to investigate.

**Pull request closed without merging**
